sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPS=1
before_install: 
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-345521
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials k8s-multicluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --pasword-stdin
  - docker build -t shomare/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true shomare/react-test npm test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
